// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///
// /
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3q0TafO1AcWqoEhpHfn1WNZbTo1tejqg',
    appId: '1:443236312049:web:8a2b50159ed869ac671a50',
    messagingSenderId: '443236312049',
    projectId: 'scoreboard-32285',
    authDomain: 'scoreboard-32285.firebaseapp.com',
    storageBucket: 'scoreboard-32285.appspot.com',
    measurementId: 'G-9LSRQ22JXL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2Co-2dLOf54A61WpQ8p_qLEC25Nk3-4c',
    appId: '1:443236312049:android:04d7a582efe0885f671a50',
    messagingSenderId: '443236312049',
    projectId: 'scoreboard-32285',
    storageBucket: 'scoreboard-32285.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIYNBsrKIcoAvoDZNikKC_FQZB2X_umHk',
    appId: '1:443236312049:ios:97e38418543425a0671a50',
    messagingSenderId: '443236312049',
    projectId: 'scoreboard-32285',
    storageBucket: 'scoreboard-32285.appspot.com',
    iosBundleId: 'com.example.scorreBoardFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIYNBsrKIcoAvoDZNikKC_FQZB2X_umHk',
    appId: '1:443236312049:ios:97e38418543425a0671a50',
    messagingSenderId: '443236312049',
    projectId: 'scoreboard-32285',
    storageBucket: 'scoreboard-32285.appspot.com',
    iosBundleId: 'com.example.scorreBoardFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3q0TafO1AcWqoEhpHfn1WNZbTo1tejqg',
    appId: '1:443236312049:web:8a2b50159ed869ac671a50',
    messagingSenderId: '443236312049',
    projectId: 'scoreboard-32285',
    authDomain: 'scoreboard-32285.firebaseapp.com',
    storageBucket: 'scoreboard-32285.appspot.com',
    measurementId: 'G-9LSRQ22JXL',
  );
}
